#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 16, 2018 01:20:40 PM CET  platform: Windows NT

import sys
import bot2048 as bot
from threading import Thread
import webbrowser

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import app_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    app_support.set_Tk_var()
    top = Toplevel1 (root)
    app_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    app_support.set_Tk_var()
    top = Toplevel1 (w)
    app_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font11 = "-family Arial -size 14 -weight normal -slant roman -underline 0 -overstrike 0"

        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("430x270+578+244")
        top.title("2048 Bot")
        top.configure(background="#fff")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.022, rely=0.04, height=30, width=168)
        self.Label1.configure(background="#fff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="Arial")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Game dimension:''')

        self.dimensionCombo = ttk.Combobox(top)
        self.dimensionCombo.place(relx=0.422, rely=0.037, relheight=0.115
                , relwidth=0.54)
        self.value_list = ['4x4','5x5','8x8']
        self.dimensionCombo.configure(values=self.value_list)
        self.dimensionCombo.configure(textvariable=app_support.combobox)
        self.dimensionCombo.configure(takefocus="")
        self.dimensionCombo.configure(state="readonly")
        self.dimensionCombo.current(0)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.022, rely=0.24, height=30, width=97)
        self.Label2.configure(background="#fff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="Arial")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Algorithm:''')

        self.algCombo = ttk.Combobox(top)
        self.algCombo.place(relx=0.422, rely=0.222, relheight=0.115
                , relwidth=0.54)
        self.value_list2 = ['Random','Greedy','Monotonic Decreasing','Minimax']
        self.algCombo.configure(values=self.value_list2)
        self.algCombo.configure(textvariable=app_support.combobox2)
        self.algCombo.configure(takefocus="")
        self.algCombo.configure(state="readonly")
        self.algCombo.current(0)

        self.startButton = tk.Button(top)
        self.startButton.place(relx=0.628, rely=0.407, height=40, width=150)
        self.startButton.configure(activebackground="#ececec")
        self.startButton.configure(activeforeground="#000000")
        self.startButton.configure(background="#005b96")
        self.startButton.configure(disabledforeground="#a3a3a3")
        self.startButton.configure(font="Arial")
        self.startButton.configure(foreground="#fff")
        self.startButton.configure(highlightbackground="#005b96")
        self.startButton.configure(highlightcolor="black")
        self.startButton.configure(pady="0")
        self.startButton.configure(text='''Start''')
        self.startButton.bind('<Button-1>', self.startPlayingButton)

        self.stopButton = tk.Button(top)
        self.stopButton.place(relx=0.628, rely=0.593, height=42, width=150)
        self.stopButton.configure(activebackground="#ececec")
        self.stopButton.configure(activeforeground="#000000")
        self.stopButton.configure(background="#ff6f69")
        self.stopButton.configure(disabledforeground="#a3a3a3")
        self.stopButton.configure(foreground="#fff")
        self.stopButton.configure(highlightbackground="#d9d9d9")
        self.stopButton.configure(highlightcolor="black")
        self.stopButton.configure(pady="0")
        self.stopButton.configure(text='''Stop''')
        self.stopButton.bind('<Button-1>', self.stopPlayingButton)

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.023, rely=0.407, relheight=0.386 , relwidth=0.511)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="Arial")
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Status''')
        self.Labelframe1.configure(background="#fff")
        self.Labelframe1.configure(width=230)
  
        self.statusLabel = tk.Label(self.Labelframe1)
        self.statusLabel.place(relx=0.043, rely=0.353, height=38, width=140, bordermode='ignore')
        self.statusLabel.configure(background="#fff")
        self.statusLabel.configure(disabledforeground="#a3a3a3")
        self.statusLabel.configure(font=font11)
        self.statusLabel.configure(foreground="#000000")
        self.statusLabel.configure(text='''STOPPED''')

        self.browserButton = tk.Button(top)
        self.browserButton.place(relx=0.023, rely=0.815, height=42, width=410)
        self.browserButton.configure(activebackground="#ececec")
        self.browserButton.configure(activeforeground="#000000")
        self.browserButton.configure(background="#fff")
        self.browserButton.configure(disabledforeground="#a3a3a3")
        self.browserButton.configure(font="Arial")
        self.browserButton.configure(foreground="#000000")
        self.browserButton.configure(highlightbackground="#d9d9d9")
        self.browserButton.configure(highlightcolor="black")
        self.browserButton.configure(pady="0")
        self.browserButton.configure(text='''Start game in browser''')
        self.browserButton.configure(width=410)
        self.browserButton.bind('<Button-1>', self.openBrowserButton)


        self.thread = None
    
    def openBrowserButton(self, event):
        webbrowser.open('http://2048game.com/')

    def startPlayingButton(self, event):
        selectedDim = self.dimensionCombo.get()
        self.dimension = int(selectedDim[0])
        self.alg = self.algCombo.get()
        self.thread = Thread(target = self.startBot)
        self.thread.start()
        self.statusLabel.configure(text="RUNNING")
    
    def startBot(self):
        bot.startPlaying(self.dimension, self.alg)
        self.statusLabel.configure(text="STOPPED")
    
    def stopPlayingButton(self, event):
        bot.stopPlaying()
        self.statusLabel.configure(text="STOPPED")

if __name__ == '__main__':
    vp_start_gui()





